### ISSUE TITLE
Spike: confirm if controlled vocabularies work from the profile

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#960]
## Summary
Confirm if controlled vocabularies we have set up in the past work, using the name and profile

## Acceptance Criteria
- [ ] The above is confirmed and follow up tickets (if needed) are created

**Comment by ShanaLMoore** [comment]
I don't think this works. I tried referencing 'audience' as a source for a field called "additional_information" and was hoping to see the form display the audience values from config/authorities/audience.yml. It does not: 

```
  additional_information:
    available_on:
      class:
      - OerResource
      - EtdResource
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - audience
    display_label:
      default: Additional Information
    index_documentation: searchable
    indexing:
    - additional_information_tesim
    form:
      primary: true
      multiple: true
    property_uri: http://purl.org/dc/terms/accessRights
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - This is some additional information.
    - More details and context.
 ```

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/89cbcb6d-4e93-4596-849d-e7b267c06a39" />

cc @orangewolf Did I misunderstand you?
